spring:
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AQAc6cjCJrf73WSQfoMZdXaA5FHGULGa7SN8P/ke3TF8NXkNIs510itfhhKEPu93MLbqDLDLbd5loRDSSGLthtUbLTAM9yE9LsctnT5FHeDrCf0NCOlHISBR0VSWciFOA2CoLWxCNh542Yxmbgn8NoTx+kwDYNSrM4jPoRFNLdT4dcuuUMyJsvTT4M2KPQKxtiENKwPhGLH0fsuJRZiICCuJIZPg9Z0vwshRwuwu4cNUDoor4XeLvmbL4ya/z5AY6wDbs82o7I2iFeALBpStcnknekSLMwL7CGU5d7dhOsmgF4qy3CPIbmyMmpJUrU75i8/UnRM5PvVqce+/4j6JHmfJ0aSqdphOjgS5Epzt494/GzVdn78XDlNtU1n8iXYWWtg='

token:
  expiration_time: 86400000
  # secret: my_token_native_user_service_defalut
  secret: '{cipher}AQAFlLPhX50U2Zb3mNWHh8bVBgX7EK2orh4KISahL6al5KgSeBPqT7wTtU3KnM2QjPtp5M+8QIjOK6sgRDA1/JFoDyi0sVc1YNB0WA0Z8xZuKyIoeadcTizXruGnFHoLcaETSFXv3AvTU+f7AalIeI//YCoosH2Kj3hgwOYAGKLk/WSV4FqguxvsT0kFzgU4PgvA7whIuaHaNbmWD555CvJkqMZGahbwvkCcViQR/DdodaoHqe5TFrFSQQsnH/InM3pa41k7zSb5mwSzFpKHmL546ACy7QRVZPGYEGHSVv+pwtQ9USPUXV/WJQkK11LOaWpdAdwYjvyn84xy1XmopMfYr4Yg3xkThWVUbS5CSJIx4CyypX5VAAM/94HpoCNOAJ4cFHVVQYeaGruEuI5B2+U+'

gateway:
  #ip: 172.30.1.62
  #ip: 192.168.70.169
  ip: 172.18.0.5 
#test
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception: 
    orders_is_empty: There is no users.